#ifndef ENTRY
#define ENTRY
#include "public.h"
EFI_STATUS EFIAPI FhhfsDriverBindingSupported(IN EFI_DRIVER_BINDING_PROTOCOL *This,IN EFI_HANDLE ControllerHandle,IN EFI_DEVICE_PATH_PROTOCOL *RemainingDevicePath OPTIONAL);
EFI_STATUS EFIAPI FhhfsDriverBindingStart(IN EFI_DRIVER_BINDING_PROTOCOL *This,IN EFI_HANDLE ControllerHandle,IN EFI_DEVICE_PATH_PROTOCOL *RemainingDevicePath OPTIONAL);
EFI_STATUS EFIAPI FhhfsDriverBindingStop(IN EFI_DRIVER_BINDING_PROTOCOL *This,IN EFI_HANDLE ControllerHandle,IN  UINTN NumberOfChildren,IN  EFI_HANDLE *ChildHandleBuffer OPTIONAL);
EFI_STATUS EFIAPI FhhFsGetDriverName(IN EFI_COMPONENT_NAME2_PROTOCOL *This,IN CHAR8 *Language,OUT CHAR16 **DriverName);
EFI_STATUS EFIAPI FhhFsGetControllerName(IN EFI_COMPONENT_NAME2_PROTOCOL *This,IN EFI_HANDLE ControllerHandle,IN EFI_HANDLE ChildHandle OPTIONAL,IN CHAR8 *Language,OUT CHAR16 **ConName);
#endif
